/* EduPath BD — Demo data
   56 verified testimonials from the cleaned 2024 student/graduate survey.
   15 subjects with full profiles (Verified or Emerging tier).
   16 additional subjects appear in Stories only (Listed-only tier; no profile card).
   Source files:
     - uploads/testimonials_clean.json
     - uploads/EduPathBD_Cleaned_Dataset.xlsx
   Schema mirrors the build plan §5.3 (subjects, testimonials, fields). */

window.PFData = (function () {
  const FIELDS = {
    technology:       { label: "Engineering & Technology",  color: "#2A6FDB" },
    business:         { label: "Business & Commerce",       color: "#B07A1F" },
    science:          { label: "Natural Sciences",          color: "#5C8C3E" },
    "social-science": { label: "Social Sciences",           color: "#8E5BB7" },
    humanities:       { label: "Arts & Humanities",         color: "#C8553D" },
    environmental:    { label: "Life & Earth Sciences",     color: "#2F8F6A" },
    design:           { label: "Design",                    color: "#D97757" },
    applied:          { label: "Health & Medicine",         color: "#4F5D75" },
  };

  // Confidence tier names follow the EduPath BD Build Plan §4.1:
  //   verified   — verified course profile + 8+ approved testimonials
  //   emerging   — profile present OR 3–7 testimonials
  //   listed     — fewer than 3 testimonials, no verified profile
  // Computed on the fly in computeConfidence(); the value stamped on each subject
  // is the EXPECTED tier at the current dataset size, kept honest with the data.

  const subjects = [

    {
      slug: "cse",
      name: "Computer Science & Engineering",
      field: "technology",
      desc: "Software, systems, AI — the backbone of modern work.",
      hsc: ["Science"],
      math: true,
      difficulty: 3,
      trend: "rising",
      regional: {
        dhaka: {
          careers: ["Software Engineer", "Data Scientist", "IT Manager", "Cybersecurity Analyst"],
          salary: "৳30k–2L+/mo",
          note: "85% of BD software roles are in Dhaka. Outside-Dhaka graduates report a 30–40% initial salary gap. Remote work is growing but not standard.",
        },
        outside: {
          careers: ["Govt IT officer (BCS)", "Lecturer / Teacher", "NGO field coordinator", "Local startup / freelance"],
          salary: "৳15k–80k/mo",
          note: "Outside Dhaka, CSE graduates typically target BCS, teaching, or build local freelance practices. Remote work for Dhaka/global companies is rising but requires portfolio strength.",
        },
        intl: {
          careers: ["ML Research Scientist", "Cloud Architect", "Silicon Valley SWE", "Tech Entrepreneur"],
          salary: "$80k–$180k/yr",
        },
      },
      curriculum: [
        { year: "Year 1", title: "Foundation",       items: ["Math & Logic", "Intro to Code", "Digital Logic"], note: "Many students struggle here", noteTone: "warn" },
        { year: "Year 2", title: "Core Systems",     items: ["Database", "Networking", "Algorithms"],          note: "Most intensive semester is Y2S2", noteTone: "warn" },
        { year: "Year 3", title: "Specialisation",   items: ["AI / ML", "Data Science", "Cyber Security"],     note: null },
        { year: "Year 4", title: "Capstone",         items: ["Industry Project", "Research Paper", "Job Readiness"], note: "80% employed within 6 months", noteTone: "good" },
      ],
      unis: { public: ["BUET", "KUET", "RUET", "CUET"], private: ["BRAC University", "NSU", "DIU", "AIUB", "EWU"] },
      alts: ["uiux", "development-studies", "economics"],
      confidence: "verified",
    },
    {
      slug: "agriculture",
      name: "Agriculture",
      field: "environmental",
      desc: "Field work, food systems, applied biology.",
      hsc: ["Science"],
      math: false,
      difficulty: 2,
      trend: "stable",
      regional: {
        dhaka: { careers: ["Agritech analyst", "Research assistant", "Govt agriculture officer"], salary: "৳25k–70k/mo",
          note: "Most senior research and agritech roles still cluster around Dhaka and Gazipur. Field roles are equally distributed nationally."},
        outside: { careers: ["BCS Agriculture cadre", "NGO field officer (BRAC, Grameen)", "Cooperative agronomist", "Local farm tech consultant"], salary: "৳18k–55k/mo",
          note: "Outside Dhaka is the natural home for this subject — most jobs ARE outside Dhaka. The BCS Agriculture cadre is a strong public-sector path."},
        intl: { careers: ["Food systems researcher", "FAO / WFP analyst", "Agronomy PhD pathways"], salary: "$45k–$95k/yr" },
      },
      curriculum: [
        { year: "Year 1", title: "Foundation",   items: ["Plant biology", "Soil basics", "Field methods"], note: "Field work starts in week 3 — be ready", noteTone: "good" },
        { year: "Year 2", title: "Core Systems", items: ["Crop sciences", "Animal husbandry", "Genetics"], note: null },
        { year: "Year 3", title: "Specialisation", items: ["Agribusiness", "Horticulture", "Aquaculture"], note: null },
        { year: "Year 4", title: "Capstone",     items: ["Thesis project", "Internship", "BCS preparation"], note: "Strong public-sector outcomes", noteTone: "good" },
      ],
      unis: { public: ["BAU (Mymensingh)", "SAU (Dhaka)", "BSMRAU", "PSTU"], private: ["—"] },
      alts: ["environmental", "biology"],
      confidence: "emerging",
    },
    {
      slug: "bba",
      name: "Business Administration (BBA)",
      field: "business",
      desc: "Management, finance, marketing — broad, applied, employable.",
      hsc: ["Science", "Commerce"],
      math: false,
      difficulty: 2,
      trend: "stable",
      regional: {
        dhaka: { careers: ["Management trainee", "Brand executive", "Bank officer", "Consultant"], salary: "৳25k–1L+/mo",
          note: "Top private universities recruit heavily for management trainee programs in Dhaka. Network effects compound here." },
        outside: { careers: ["Local bank officer", "MFI manager", "Family business operator", "Sales lead"], salary: "৳18k–60k/mo",
          note: "Outside Dhaka, BBA is most useful for joining local banks, MFIs, and helping run family businesses." },
        intl: { careers: ["MBA pathway (post-3yr work)", "Multinational management programs"], salary: "$60k–$150k/yr" },
      },
      curriculum: [
        { year: "Year 1", title: "Foundation",   items: ["Principles of Mgmt", "Financial Accounting", "Microeconomics"], note: null },
        { year: "Year 2", title: "Core Systems", items: ["Marketing", "HR", "Statistics"], note: null },
        { year: "Year 3", title: "Specialisation", items: ["Finance", "Brand", "Operations"], note: null },
        { year: "Year 4", title: "Capstone",     items: ["Internship", "Capstone project"], note: "Most students placed via internship pipelines", noteTone: "good" },
      ],
      unis: { public: ["DU (IBA)", "JU", "RU", "CU"], private: ["NSU", "BRAC University", "EWU", "IUB", "AIUB"] },
      alts: ["economics", "finance-banking"],
      confidence: "verified",
    },
    {
      slug: "economics",
      name: "Economics",
      field: "social-science",
      desc: "How resources, people, and policy actually move.",
      hsc: ["Science", "Commerce"],
      math: true,
      difficulty: 3,
      trend: "rising",
      regional: {
        dhaka: { careers: ["Policy analyst", "Research economist", "Bank economist", "Think tank associate"], salary: "৳30k–1.2L+/mo",
          note: "Most policy think tanks (CPD, PRI, BIDS) are Dhaka-centred." },
        outside: { careers: ["BCS economic cadre", "NGO researcher", "Local research assistant", "University teaching"], salary: "৳18k–60k/mo",
          note: "Outside Dhaka, the BCS economic cadre and NGO research roles dominate. Academic pathway is realistic." },
        intl: { careers: ["IMF / World Bank associate", "Economics PhD", "Quant researcher"], salary: "$70k–$160k/yr" },
      },
      curriculum: [
        { year: "Year 1", title: "Foundation",   items: ["Micro", "Macro", "Math for Economists"], note: "Math is heavier than students expect", noteTone: "warn" },
        { year: "Year 2", title: "Core Systems", items: ["Econometrics", "Development", "Public Finance"], note: null },
        { year: "Year 3", title: "Specialisation", items: ["Behavioural Econ", "Trade", "Game Theory"], note: null },
        { year: "Year 4", title: "Capstone",     items: ["Thesis", "Statistical project"], note: null },
      ],
      unis: { public: ["DU", "JU", "CU", "RU"], private: ["NSU", "BRAC University", "EWU"] },
      alts: ["bba", "development-studies"],
      confidence: "emerging",
    },
    {
      slug: "uiux",
      name: "Graphic & UI/UX Design",
      field: "design",
      desc: "Visual systems, products, and the craft of how things feel.",
      hsc: ["Science", "Commerce", "Arts"],
      math: false,
      difficulty: 2,
      trend: "rising",
      regional: {
        dhaka: { careers: ["UI/UX designer", "Brand designer", "Product designer", "Agency creative"], salary: "৳25k–1.5L+/mo",
          note: "Dhaka's product/agency scene hires strongly on portfolio, weakly on degree. Show work, not transcripts." },
        outside: { careers: ["Freelance designer", "Local print/agency work", "Remote contract design"], salary: "৳15k–80k/mo",
          note: "Outside Dhaka, freelance + remote contract work is the realistic path. Portfolio strength matters more than location." },
        intl: { careers: ["Remote product designer", "Studio designer (Dribbble-pipeline)", "EU/US design teams"], salary: "$55k–$140k/yr" },
      },
      curriculum: [
        { year: "Year 1", title: "Foundation",   items: ["Drawing", "Type & Color", "Composition"], note: null },
        { year: "Year 2", title: "Core Systems", items: ["Branding", "Editorial", "UI fundamentals"], note: null },
        { year: "Year 3", title: "Specialisation", items: ["Product / UX", "Motion", "3D / Illustration"], note: null },
        { year: "Year 4", title: "Capstone",     items: ["Portfolio", "Industry project", "Internship"], note: "Portfolio > grades, every time", noteTone: "good" },
      ],
      unis: { public: ["DU (Fine Arts)", "Charukola (Chittagong)"], private: ["Pathshala", "ULAB", "BRAC University"] },
      alts: ["cse", "english-lit"],
      confidence: "emerging",
    },
    {
      slug: "english-lit",
      name: "English Literature",
      field: "humanities",
      desc: "Close reading, writing, cultures, criticism.",
      hsc: ["Science", "Commerce", "Arts"],
      math: false,
      difficulty: 2,
      trend: "stable",
      regional: {
        dhaka: { careers: ["Editor / Sub-editor", "Content strategist", "Communications lead", "Teacher"], salary: "৳18k–80k/mo",
          note: "Most publishing, NGO communications, and content roles are Dhaka-based." },
        outside: { careers: ["Secondary / college teacher", "BCS education cadre", "NGO communications"], salary: "৳15k–45k/mo",
          note: "Teaching and government cadre are the dominant outside-Dhaka pathways." },
        intl: { careers: ["MA pathway abroad", "Editorial assistant", "Localization specialist"], salary: "$35k–$70k/yr" },
      },
      curriculum: [
        { year: "Year 1", title: "Foundation",   items: ["Survey of literature", "Composition", "Linguistics"], note: null },
        { year: "Year 2", title: "Core Systems", items: ["Periods (Renaissance/Modern)", "Drama", "Poetry"], note: null },
        { year: "Year 3", title: "Specialisation", items: ["Post-colonial", "Theory", "Comparative"], note: null },
        { year: "Year 4", title: "Capstone",     items: ["Thesis", "Teaching practicum"], note: null },
      ],
      unis: { public: ["DU", "JU", "RU", "CU"], private: ["NSU", "BRAC University", "EWU"] },
      alts: ["development-studies", "uiux"],
      confidence: "emerging",
    },
    {
      slug: "development-studies",
      name: "Development Studies",
      field: "social-science",
      desc: "Poverty, policy, NGOs, and the field work that drives change.",
      hsc: ["Science", "Commerce", "Arts"],
      math: false,
      difficulty: 2,
      trend: "rising",
      regional: {
        dhaka: { careers: ["NGO program officer", "Policy research", "Donor agency role"], salary: "৳25k–80k/mo",
          note: "Bangladesh is a global NGO hub — BRAC, Grameen, donor agencies all hire heavily in Dhaka." },
        outside: { careers: ["NGO field officer", "Local government", "Microfinance"], salary: "৳18k–50k/mo",
          note: "Outside Dhaka is where the actual development work happens — most field roles are here." },
        intl: { careers: ["UN agency", "World Bank consultant", "MA Development abroad"], salary: "$50k–$110k/yr" },
      },
      curriculum: [
        { year: "Year 1", title: "Foundation",   items: ["Theories of development", "Sociology", "Stats basics"], note: null },
        { year: "Year 2", title: "Core Systems", items: ["Poverty & inequality", "Governance", "Research methods"], note: null },
        { year: "Year 3", title: "Specialisation", items: ["Gender", "Rural / Urban", "Climate"], note: null },
        { year: "Year 4", title: "Capstone",     items: ["Fieldwork", "Thesis"], note: "Fieldwork placement is the most career-defining part", noteTone: "good" },
      ],
      unis: { public: ["DU", "JU", "BRAC University (DS dept.)"], private: ["BRAC University", "ULAB", "EWU"] },
      alts: ["economics", "english-lit"],
      confidence: "emerging",
    },
    {
      slug: "geography",
      name: "Geography & Environment",
      field: "environmental",
      desc: "Land, climate, GIS, and how Bangladesh's geography shapes everything.",
      hsc: ["Science"],
      math: false,
      difficulty: 2,
      trend: "rising",
      regional: {
        dhaka: { careers: ["GIS analyst", "Climate research", "Urban planning consultant"], salary: "৳25k–75k/mo",
          note: "Urban planning, climate adaptation, and donor-funded GIS work is concentrated in Dhaka." },
        outside: { careers: ["BCS administration / forest cadre", "NGO climate field officer", "Local planning office"], salary: "৳18k–55k/mo",
          note: "Coastal and northern districts have growing climate-adaptation roles funded by international donors." },
        intl: { careers: ["GIS specialist", "Climate research abroad", "Remote-sensing analyst"], salary: "$50k–$95k/yr" },
      },
      curriculum: [
        { year: "Year 1", title: "Foundation",   items: ["Physical geography", "Cartography", "Earth systems"], note: null },
        { year: "Year 2", title: "Core Systems", items: ["Human geography", "GIS intro", "Climatology"], note: null },
        { year: "Year 3", title: "Specialisation", items: ["Remote sensing", "Urban", "Environmental policy"], note: null },
        { year: "Year 4", title: "Capstone",     items: ["Field study", "Thesis"], note: null },
      ],
      unis: { public: ["DU", "JU", "RU", "CU", "NSTU"], private: ["—"] },
      alts: ["agriculture", "development-studies"],
      confidence: "emerging",
    },
    {
      slug: "finance-banking",
      name: "Finance & Banking",
      field: "business",
      desc: "Capital markets, banking, risk — quantitative, structured, employable.",
      hsc: ["Science", "Commerce"],
      math: true,
      difficulty: 3,
      trend: "stable",
      regional: {
        dhaka: { careers: ["Investment analyst", "Risk officer", "Treasury", "Audit"], salary: "৳30k–1.2L+/mo",
          note: "All major banks, brokerages, and asset managers are headquartered in Dhaka." },
        outside: { careers: ["Branch banking", "BCS administration", "Local audit firm"], salary: "৳20k–55k/mo",
          note: "Outside Dhaka, branch banking and BCS administration are the dominant paths." },
        intl: { careers: ["CFA pathway", "International audit", "Risk analyst abroad"], salary: "$60k–$140k/yr" },
      },
      curriculum: [
        { year: "Year 1", title: "Foundation",   items: ["Accounting", "Microeconomics", "Quant methods"], note: null },
        { year: "Year 2", title: "Core Systems", items: ["Corporate finance", "Banking ops", "Statistics"], note: null },
        { year: "Year 3", title: "Specialisation", items: ["Investments", "Risk management", "Financial modelling"], note: null },
        { year: "Year 4", title: "Capstone",     items: ["CFA prep", "Internship", "Thesis"], note: "CFA Level 1 during final year is common", noteTone: "good" },
      ],
      unis: { public: ["DU", "CU", "JU"], private: ["NSU", "BRAC University", "EWU", "AIUB"] },
      alts: ["bba", "economics"],
      confidence: "verified",
    },
    {
      slug: "physics",
      name: "Physics",
      field: "science",
      desc: "Classical mechanics, quantum, electrodynamics — pure science with a heavy theory load.",
      hsc: ["Science"],
      math: true,
      difficulty: 4,
      trend: "niche",
      curriculumStyle: "vertical",
      regretSignal: { rate: 50, note: "Half of the Physics respondents in our dataset explicitly regret the choice. The single recurring complaint: the national curriculum never teaches the computational programming you need to actually do modern physics." },
      regional: {
        dhaka: { careers: ["Private tutor (high-paying)", "Research assistant (university)", "Corporate analytics generalist"], salary: "৳25k–65k/mo",
          note: "Research infrastructure and serious physics-track tutoring is concentrated at DU/BUET. Most Dhaka-based Physics graduates pivot into private tutoring or generalist analytics; pure-physics roles are rare outside academia." },
        outside: { careers: ["College / school teacher", "BCS general cadre"], salary: "৳15k–40k/mo",
          note: "Outside Dhaka, college teaching and BCS general cadre are essentially the only paths. Industry rarely hires Physics graduates as Physics graduates." },
        intl: { careers: ["MS / PhD pathway (the dominant route)", "Computational physics / quant adjacent"], salary: "$45k–$130k/yr (post-PhD)" },
      },
      curriculum: [
        { year: "Years 1–2", title: "Classical frameworks & calculus", items: ["Vector analysis & Newtonian mechanics", "Waves and optics", "Multivariable calculus, ODEs"], note: "Heavily theoretical. No programming taught — you'll need to learn it on your own", noteTone: "warn" },
        { year: "Years 3–4", title: "Advanced quantum dynamics", items: ["Statistical mechanics", "Modern electrodynamics", "Solid state, lab thesis modules"], note: "Computational gap becomes painful here — most research now requires Python/MATLAB", noteTone: "warn" },
      ],
      unis: { public: ["DU", "JU", "CU", "RU", "BUET (Physics dept.)"], private: ["—"] },
      alts: ["cse", "agriculture"],
      confidence: "listed",
    },
    {
      slug: "journalism",
      name: "Journalism & Media Studies",
      field: "humanities",
      desc: "Reporting, broadcasting, content production — creatively rich, financially precarious.",
      hsc: ["Science", "Commerce", "Arts"],
      math: false,
      difficulty: 2,
      trend: "stable",
      curriculumStyle: "vertical",
      regretSignal: { rate: 60, note: "Multiple respondents say flatly: don't take this subject in Bangladesh until media wages improve. The creative work is real; the pay isn't." },
      regional: {
        dhaka: { careers: ["TV reporter / producer", "Online news editor", "Brand content / agency creative"], salary: "৳18k–60k/mo",
          note: "All major TV networks and newspapers are headquartered in Dhaka. Baseline wages are persistently low — the creative ceiling is high but pay rarely matches." },
        outside: { careers: ["Local stringer", "District correspondent", "Freelance content"], salary: "৳10k–25k/mo",
          note: "Outside Dhaka, journalism is almost entirely stringer work and underpaid. Most graduates pivot out within five years." },
        intl: { careers: ["MA in media abroad", "Production / content roles overseas", "Freelance + remote"], salary: "$35k–$70k/yr" },
      },
      curriculum: [
        { year: "Years 1–2", title: "Foundation — reporting & media theory", items: ["News writing & reporting basics", "Media history & ethics", "Camera and field exercises"], note: "The practical labs are genuinely good", noteTone: "good" },
        { year: "Years 3–4", title: "Specialisation — production & projects", items: ["TV / broadcast production", "Specialised reporting beats", "Capstone documentary / thesis"], note: "The career gap shows up around graduation — wages start so low that most pivot", noteTone: "warn" },
      ],
      unis: { public: ["DU", "JU", "RU", "CU"], private: ["ULAB", "DIU"] },
      alts: ["english-lit", "uiux", "development-studies"],
      confidence: "listed",
    },
    {
      slug: "psychology",
      name: "Psychology",
      field: "social-science",
      desc: "How minds and behaviour work — clinical, research, and applied.",
      hsc: ["Science", "Commerce", "Arts"],
      math: false,
      difficulty: 2,
      trend: "rising",
      regional: {
        dhaka: { careers: ["Clinical counsellor", "Therapist (post-MA)", "UX researcher", "HR specialist"], salary: "৳25k–80k/mo",
          note: "Mental health is a rapidly growing field in Dhaka, but most clinical practice requires an MA." },
        outside: { careers: ["School counsellor", "NGO mental health field officer"], salary: "৳18k–45k/mo",
          note: "Outside Dhaka, school counselling and NGO field work are the main openings — clinical practice is sparse." },
        intl: { careers: ["MA / PhD pathway abroad", "Research assistant"], salary: "$45k–$95k/yr" },
      },
      curriculum: [
        { year: "Year 1", title: "Foundation",   items: ["Intro psych", "Stats", "Biological basis"], note: null },
        { year: "Year 2", title: "Core Systems", items: ["Developmental", "Social", "Cognitive"], note: null },
        { year: "Year 3", title: "Specialisation", items: ["Clinical", "Organisational", "Counselling"], note: null },
        { year: "Year 4", title: "Capstone",     items: ["Research thesis", "Internship"], note: "MA is effectively required for clinical work", noteTone: "warn" },
      ],
      unis: { public: ["DU", "JU", "CU", "RU"], private: ["BRAC University", "NSU"] },
      alts: ["development-studies", "english-lit"],
      confidence: "listed",
    },

    {
      slug: "bangla",
      name: "Bangla",
      field: "humanities",
      desc: "Literature, language, criticism — the national tongue, studied seriously.",
      hsc: ["Science", "Commerce", "Arts"],
      math: false,
      difficulty: 2,
      trend: "stable",
      curriculumStyle: "vertical",
      regional: {
        dhaka: { careers: ["Editorial / publishing", "School & college teaching", "NGO communications", "Cultural sector"], salary: "৳15k–60k/mo",
          note: "Most respondents work as teachers or in publishing. The Bangla literary scene is Dhaka-centred but the teaching path is national." },
        outside: { careers: ["BCS education cadre", "College / school teacher", "Local publishing & culture work"], salary: "৳12k–40k/mo",
          note: "Outside Dhaka, teaching and BCS education cadre are the dominant pathways. Stable, modest, respected work." },
        intl: { careers: ["MA in Bangla / South Asian studies abroad", "Translation / language work"], salary: "$25k–$55k/yr" },
      },
      curriculum: [
        { year: "Years 1–2", title: "Foundation — language & history", items: ["Bangla grammar & linguistics", "Survey of Bangla literature", "Poetry & prose traditions"], note: null },
        { year: "Years 3–4", title: "Specialisation & thesis", items: ["Modernist & post-colonial criticism", "Comparative literature options", "Capstone thesis"], note: "Strong fit for teaching-track aspirants", noteTone: "good" },
      ],
      unis: { public: ["DU", "JU", "RU", "CU", "Jagannath University"], private: ["—"] },
      alts: ["english-lit", "development-studies"],
      confidence: "emerging",
    },
    {
      slug: "civil-engineering",
      name: "Civil Engineering",
      field: "technology",
      desc: "Structures, transport, water — the physical infrastructure of the country.",
      hsc: ["Science"],
      math: true,
      difficulty: 4,
      trend: "stable",
      curriculumStyle: "vertical",
      regional: {
        dhaka: { careers: ["Structural / site engineer", "Consulting firm", "Real-estate developer", "Govt PWD"], salary: "৳35k–1.2L+/mo",
          note: "Dhaka has the largest concentration of consulting firms and high-rise developers. Site work is national." },
        outside: { careers: ["Site engineer (national rotation)", "LGED / PWD postings", "BCS engineering cadre", "Local contractor"], salary: "৳25k–70k/mo",
          note: "Civil engineering is one of the few subjects where outside-Dhaka work is the norm, not a fallback. National infrastructure work pays decently." },
        intl: { careers: ["MS abroad (structural / transportation)", "Gulf / Middle East site work"], salary: "$45k–$110k/yr" },
      },
      curriculum: [
        { year: "Years 1–2", title: "Foundation — mechanics & math", items: ["Engineering mechanics", "Strength of materials", "Calculus & numerical methods"], note: "Theory load is heavy — the math doesn't let up", noteTone: "warn" },
        { year: "Years 3–4", title: "Specialisation & site work", items: ["Structural / geotechnical / transport", "Hydraulics & water resources", "Capstone design project"], note: "Final-year placement is the most career-defining moment", noteTone: "good" },
      ],
      unis: { public: ["BUET", "KUET", "RUET", "CUET", "IUT"], private: ["AIUB", "BRAC University", "IUB"] },
      alts: ["cse", "geography"],
      confidence: "emerging",
    },
    {
      slug: "mathematics",
      name: "Mathematics",
      field: "science",
      desc: "Pure proofs, applied stats, the language behind everything technical.",
      hsc: ["Science"],
      math: true,
      difficulty: 4,
      trend: "rising",
      curriculumStyle: "vertical",
      regretSignal: { rate: 33, note: "One of our three Mathematics respondents flatly says: 'I would choose Computer Science. Because of demand in higher studies.' The pure-math route is a respected academic path — but the demand gap with CSE is real, and worth knowing before you sign up." },
      regional: {
        dhaka: { careers: ["Quant / data analyst (pivot)", "Actuarial / risk", "University teaching (post-MS)", "Statistical consulting"], salary: "৳25k–80k/mo",
          note: "Most Math graduates in Dhaka pivot into data, finance, or actuarial roles. Pure-math jobs are essentially academia." },
        outside: { careers: ["College / school teacher", "BCS education / general cadre", "Statistics-adjacent govt roles"], salary: "৳15k–45k/mo",
          note: "Outside Dhaka, teaching and BCS are the dominant paths. Stable but slow-growing." },
        intl: { careers: ["MS / PhD abroad", "Quant / data science globally"], salary: "$60k–$160k/yr" },
      },
      curriculum: [
        { year: "Years 1–2", title: "Foundation — calculus & algebra", items: ["Single & multivariable calculus", "Linear algebra & ODEs", "Discrete math & logic"], note: null },
        { year: "Years 3–4", title: "Specialisation — pure or applied", items: ["Topology, analysis, group theory (pure)", "Probability, statistics, numerical methods (applied)", "Thesis"], note: "Topology and fuzzy mathematics are the recurring pain points in our data", noteTone: "warn" },
      ],
      unis: { public: ["DU", "BUET (Math)", "JU", "CU", "RU"], private: ["BRAC University"] },
      alts: ["cse", "finance-banking", "economics"],
      confidence: "emerging",
    },
  ];


  const testimonials = [
    {
        "verified": true,
        "id": "resp_001",
        "age": "21",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "civil-engineering",
        "subjectName": "Civil & Environmental Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "Islamic University of Technology (IUT)",
        "session": "2023",
        "role": "IUT",
        "good": "Loving mechanics",
        "bad": "Hate theory courses",
        "whoShould": "Those who are good at solving mechanics",
        "whoShouldnt": "Dumb people",
        "opportunities": "Very big",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_002",
        "age": "28",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "cse",
        "subjectName": "Computer Science & Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "Bangladesh Institute of Science & Technology",
        "session": "2019",
        "role": "Hubxpert",
        "good": "That I understood it's not for me",
        "bad": "We have lack of good teachers who can grab attention of students.",
        "whoShould": "Someone who has great interest in higher level mathematics and great patience for learn coding.",
        "whoShouldnt": "Someone who is not good at math and impatient.",
        "opportunities": "In Bangladesh, except becoming an software or hardware engineer, CSE graduates can become teachers,developer,banker,service job holder etc.",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_003",
        "age": "26",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "bangla",
        "subjectName": "Bangla",
        "fieldCluster": "Arts & Humanities",
        "field": "humanities",
        "uni": "Jagannath University",
        "session": "2016",
        "role": "Gramnagar barta",
        "good": "You can feel sensations well while reading. U can see the reality of a society of a certain time. U can know people well. U can discover your inner Saul.",
        "bad": "U have to know history and understand psychology",
        "whoShould": "Who wants government job",
        "whoShouldnt": "Who wants to go abroad for higher study",
        "opportunities": "Teaching profession",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_004",
        "age": "32",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "cse",
        "subjectName": "Computer Science & Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "Daffodil International University",
        "session": "2015",
        "role": "Dproperty",
        "good": "understand it sector",
        "bad": "learned cse code by unprofessional teacher",
        "whoShould": "good at math",
        "whoShouldnt": "not good at math",
        "opportunities": "good",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_005",
        "age": "28",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "information-communication-engineering",
        "subjectName": "Information & Communication Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "Bangladesh University of Professionals (BUP)",
        "session": "2015",
        "role": "Senior Officer · Rupali Bank PLC",
        "good": "Learning new tech",
        "bad": "Too much monotonous",
        "whoShould": "People who wants to have a tech career",
        "whoShouldnt": "People who loves to explore",
        "opportunities": "This will be the next biggest industry",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_006",
        "age": "21",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "bba",
        "subjectName": "Business Administration (BBA)",
        "fieldCluster": "Business & Commerce",
        "field": "business",
        "uni": "East West University",
        "session": "Fall24",
        "role": "N/a · N/a",
        "good": "Will get the chance to work with Grameenphone and Pran soon so it will be a great experience",
        "bad": "While reading BBA we have to do a course named CSE. It isn't necessary. Cause there is actually lack of resources. We are just memorizing things",
        "whoShould": "Those people who want to be an entrepreneur or want to go for banking sector",
        "whoShouldnt": "Those who don't like the corporate job",
        "opportunities": "Dk",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_007",
        "age": "26",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "bangla",
        "subjectName": "Bangla",
        "fieldCluster": "Arts & Humanities",
        "field": "humanities",
        "uni": "Jagannath University",
        "session": "2016",
        "role": "Lecturer · Milestone College",
        "good": "This subject helped me to understand others perspection and natural beauty as well.",
        "bad": "Presentation lacking, pretty tough to get tuitions",
        "whoShould": "who loves nature, love and sit on BCS in the future",
        "whoShouldnt": "who wants to create innovative ideas, things.",
        "opportunities": "Teacher, novelist, researcher, social development activist",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_008",
        "age": "32",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "zoology",
        "subjectName": "Zoology",
        "fieldCluster": "Life & Earth Sciences",
        "field": "environmental",
        "uni": "University of Dhaka",
        "session": "2012",
        "role": "Senior officer · Meghna Bank",
        "good": "Get to understand how life and nature work intertwinedly",
        "bad": "Primitive curriculum.less opportunity of career choice",
        "whoShould": "Who has passion for life science and from a well off family",
        "whoShouldnt": "Who has to be established in his career quick and doesn't like biology much",
        "opportunities": "Computational biology",
        "again": "no",
        "alternative": "CSE"
    },
    {
        "verified": true,
        "id": "resp_009",
        "age": "30",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "bba",
        "subjectName": "Business Administration (BBA)",
        "fieldCluster": "Business & Commerce",
        "field": "business",
        "uni": "American International University-Bangladesh (AIUB)",
        "session": "2013",
        "role": "Director · Capital Builders",
        "good": "Fun Projects",
        "bad": "Lack of structures",
        "whoShould": "Who are willing to do job in future",
        "whoShouldnt": "Whom are not willing to do business",
        "opportunities": "Understanding market and organisation culture",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_010",
        "age": "30",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "geology",
        "subjectName": "Geology",
        "fieldCluster": "Life & Earth Sciences",
        "field": "environmental",
        "uni": "University of Dhaka",
        "session": "2014",
        "role": "Sales Engineer · SLB",
        "good": "Field Work",
        "bad": "Not Recognized properly",
        "whoShould": "One who have the Passion to know about the Earth Processes",
        "whoShouldnt": "Medical Lovers",
        "opportunities": "Oil and Gas Specialist",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_011",
        "age": "25",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "mbbs-medicine",
        "subjectName": "MBBS (Medicine)",
        "fieldCluster": "Health & Medicine",
        "field": "applied",
        "uni": "Armed Forces Medical College",
        "session": "2017",
        "role": "Housewife",
        "good": "Learning in organized way, group study",
        "bad": "Lack of practical experience",
        "whoShould": "Passionate to study and dedicated to treat the disease",
        "whoShouldnt": "Impatient about studying and learning",
        "opportunities": "Treat patients, teach, research",
        "again": "no",
        "alternative": "BBA/Marketting /tourism Because being a doctor is so stressful both physically and mentally"
    },
    {
        "verified": true,
        "id": "resp_012",
        "age": "23",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "cse",
        "subjectName": "Computer Science & Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "University of Liberal Arts Bangladesh (ULAB)",
        "session": "2019",
        "role": "Student · University of liberal arts",
        "good": "1. Problem-Solving and Creativity • Debugging Challenges: Solving a bug after hours of work is immensely satisfying. • Building Projects: Creating something from scratch, like apps, websites, or algorithms, allows for creativity and hands-on learning. 2. Collaborative Learning • Team Projects: Working with peers to build solutions or complete assignments fosters teamwork. • Hackathons: These events push you to think innovatively under pressure and are great learning experiences.",
        "bad": "1. Steep Learning Curve • Overwhelming Complexity: Understanding advanced concepts like machine learning, operating systems, or algorithms can be daunting. • Syntax Errors: Hours spent fixing small errors in code can be frustrating. 2. High Expectations • Heavy Workload: Balancing multiple assignments, projects, and exams can lead to burnout. • Unrealistic Deadlines: Meeting tight deadlines in both coursework and personal projects can feel overwhelming.",
        "whoShould": "Those uninterested in logical problem-solving or abstract thinking. • Individuals who dislike constant learning and adapting to new tools and technologies. • Students with little patience for trial and error, as coding and debugging often require persistence.",
        "whoShouldnt": "Choosing CSE—or any field—should depend on your interests, strengths, and long-term goals. If you’re unsure, exploring beginner programming courses or talking to current students can help you decide.",
        "opportunities": "There are many opportunities",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_013",
        "age": "27",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "civil-engineering",
        "subjectName": "Civil Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "Khulna University of Engineering & Technology (KUET)",
        "session": "2013",
        "role": "Lecturer · DCGPSC",
        "good": "Field survey",
        "bad": "Structure lab",
        "whoShould": "Who are skilled in math+phy",
        "whoShouldnt": "If u get cse/eee then avoid this",
        "opportunities": "Huge",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_014",
        "age": "27",
        "city": "Cincinnati",
        "country": "US",
        "subjectSlug": "geography",
        "subjectName": "Geography & Environment",
        "fieldCluster": "Social Sciences",
        "field": "social-science",
        "uni": "University of Dhaka",
        "session": "2016",
        "role": "Stormwater GIS analyst · Hamilton County Government Administration",
        "good": "Fieldwork",
        "bad": "Absence of technical and contemporary curriculum.",
        "whoShould": "Whoever has interest in Geography",
        "whoShouldnt": "Whoever does not find interesting",
        "opportunities": "Multitudes of opportunities, For instance, 1.physical and environment sector (water resource and management, ecology, climate change and adaptation) 2.Human geography (Society, politics, economy etc) 3.Planning (Urban and regional planning, community planning, sustainable planning, transportation planning 4.technical aspects: cartography, GIS,remote sensinng, application of satellite imagery, Please note this these are only few opportunities but not limited to.",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_015",
        "age": "26",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "uiux",
        "subjectName": "Graphic Design",
        "fieldCluster": "Arts & Humanities",
        "field": "humanities",
        "uni": "University of Dhaka",
        "session": "2016",
        "role": "Art teacher · Springdale International school",
        "good": "Realistic projects like making an entirw pop up book, illustrating everything and all of it was a great experience",
        "bad": "Lack of good printing materials and lack of clear instructions",
        "whoShould": "Anyone and everyone",
        "whoShouldnt": "Specially persons who are interested in arts",
        "opportunities": "Designer, interior designer, fashion designer, artist, teacher, coder",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_016",
        "age": "32",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "architecture",
        "subjectName": "Architecture",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "American International University-Bangladesh (AIUB)",
        "session": "2010",
        "role": "Architect · Design education for youngsters of Bangladesh",
        "good": "Lot of things to learn,inspired by great teachers & discover new myself.",
        "bad": "We dont have campus back then, but still system was good.",
        "whoShould": "Who is passionate enough to learn.",
        "whoShouldnt": "Who dont value creativity & lazy.",
        "opportunities": "Architecture blend with public administration",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_017",
        "age": "31",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "electrical-electronic-engineering",
        "subjectName": "Electrical & Electronic Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "Ahsanullah University of Science & Technology (AUST)",
        "session": "2011",
        "role": "Senior Engineer, Windows Infrastructure Operations · bKash Limited",
        "good": "Learned about how physics works by applying it in practical projects. Met some amazing professors who were like mentors.Learned a lot of basics that later helped me in my professional career.",
        "bad": "Lack of research facility, lack of funding for more complex projects.",
        "whoShould": "Those who are passionate about engineering and want to make a career out of it.",
        "whoShouldnt": "Those who are not actually passionate as it is a very challenging subject, also those who are comparatively weak in mathematics and physics",
        "opportunities": "Jobs in telecommunications, Power sector, in IT, Bank sector",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_018",
        "age": "27",
        "city": "Cumilla",
        "country": "BD",
        "subjectSlug": "agriculture",
        "subjectName": "Agriculture",
        "fieldCluster": "Life & Earth Sciences",
        "field": "environmental",
        "uni": "Noakhali Science & Technology University",
        "session": "2016",
        "role": "M.Sc in Plant Pathology · Bangladesh Agricultural University",
        "good": "It allowed me to connect more closely with nature and apply my knowledge practically at the field level, which is essential for promoting sustainable agriculture.",
        "bad": "If resources could be developed, students would have more potential in research projects.",
        "whoShould": "Students those are creative to think, interested in research.",
        "whoShouldnt": "Students who lack interest in life science.",
        "opportunities": "Agricultural scientists, Agricultural economists, Agricultural engineers, Agricultural officers (BCS), Entrepreneur in Agritech etc.",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_019",
        "age": "28",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "marketing",
        "subjectName": "Marketing",
        "fieldCluster": "Business & Commerce",
        "field": "business",
        "uni": "Jagannath University",
        "session": "2014",
        "role": "Officer · Quality Feeds Ltd.",
        "good": "Fun coursework",
        "bad": "challenging topics",
        "whoShould": "who interest accept the challenge",
        "whoShouldnt": "who can not interest accept the challenge",
        "opportunities": "Good Leader",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_020",
        "age": "26",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "english-lit",
        "subjectName": "English Language & Literature",
        "fieldCluster": "Arts & Humanities",
        "field": "humanities",
        "uni": "Jagannath University",
        "session": "2016",
        "role": "Officer · PDS International",
        "good": "There were some fun courses included. And some of our professors are really very cool. They made the journey more smooth and memorable.",
        "bad": "Literature part was not my thing",
        "whoShould": "Who really likes literature stuff",
        "whoShouldnt": "Who thinks, he/she loves English subject on the basis of their SSC and HSC curriculum 🤦‍♀️",
        "opportunities": "Teacher, Researchers",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_021",
        "age": "25",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "bangla",
        "subjectName": "Bangla",
        "fieldCluster": "Arts & Humanities",
        "field": "humanities",
        "uni": "Jagannath University",
        "session": "2017",
        "role": "Lecturer · Uttara University",
        "good": "I have been inspired to move forward despite all the adversities. I have been able to reduce greed and excessive expectations and make life easier, more beautiful, and more humane.",
        "bad": "There were some limitations in the field of research. I had fewer opportunities to conduct social research at the field level.",
        "whoShould": "I love literature, so I studied this subject.",
        "whoShouldnt": "No comment!",
        "opportunities": "Teaching, presenting, news reporter, etc.",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_022",
        "age": "30",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "finance-banking",
        "subjectName": "Finance & Banking",
        "fieldCluster": "Business & Commerce",
        "field": "business",
        "uni": "Jahangirnagar University",
        "session": "2012",
        "role": "Executive Officer · Private commerical Bank",
        "good": "related to economy",
        "bad": "Some topics are not related to our economic system.",
        "whoShould": "Those who want to build career in financial organization.",
        "whoShouldnt": "Weak in calculations",
        "opportunities": "Banks and financial organizations required skilled people having good background finance and banking",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_023",
        "age": "28",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "psychology",
        "subjectName": "Psychology",
        "fieldCluster": "Social Sciences",
        "field": "social-science",
        "uni": "University of Dhaka",
        "session": "2013",
        "role": "Psychological Counselor · IUBAT",
        "good": "Freud's theory",
        "bad": "Poor course structure and less applicability",
        "whoShould": "Who has passion about it",
        "whoShouldnt": "Less empathetic",
        "opportunities": "A huge applied areas",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_024",
        "age": "30",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "physics",
        "subjectName": "Physics",
        "fieldCluster": "Natural Sciences",
        "field": "science",
        "uni": "University of Dhaka",
        "session": "2013",
        "role": "Student",
        "good": "No good experience",
        "bad": "All bad experience",
        "whoShould": "Extremely passionate about physics and has future vision",
        "whoShouldnt": "Lack of optimism and less dedication",
        "opportunities": "Only rooppur atomic center",
        "again": "no",
        "alternative": "English"
    },
    {
        "verified": true,
        "id": "resp_025",
        "age": "29",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "economics",
        "subjectName": "Economics",
        "fieldCluster": "Social Sciences",
        "field": "social-science",
        "uni": "East West University",
        "session": "2015",
        "role": "Sr executive · PORCELANOSA",
        "good": "Interesting subject, good career potential",
        "bad": "A bit difficult on the mathematics, but EWU optimised course materials in a very good way. Sometimes faculties were a bit challenging more than subject",
        "whoShould": "Who are good at mathematics, has Patience for r&d job field, can do attitude is much needed",
        "whoShouldnt": "Weaker in maths, doesn't understand how economy works or how it contributes in bigger aspect, has different career path in mind",
        "opportunities": "Research & development, management consulting, NGO, INGO, consulting, solo researcher",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_026",
        "age": "29",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "cse",
        "subjectName": "Computer Science & Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "Bangladesh University of Business & Technology (BUBT)",
        "session": "2020",
        "role": "Graphic Designer · Navana Group",
        "good": "Feeling proud after learning tough topics and certifications.",
        "bad": "Trouble balancing theory and practical work.",
        "whoShould": "Who looking for diverse tech career options.",
        "whoShouldnt": "Individuals who dislike learning new technologies.",
        "opportunities": "Data Scientist",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_027",
        "age": "28",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "cse",
        "subjectName": "Computer Science & Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "Southeast University",
        "session": "2022",
        "role": "UI/UX Desigenr · One Information and Communication Technology",
        "good": "Real life implementation",
        "bad": "semester length and resources are not enough",
        "whoShould": "Any one who has interest in software programming , good at match and like analytics",
        "whoShouldnt": "Who don't to invest time in thinking and solving problem",
        "opportunities": "Everything is open for you as we are heading to 4th IR",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_028",
        "age": "27",
        "city": "Sylhet",
        "country": "BD",
        "subjectSlug": "philosophy",
        "subjectName": "Philosophy",
        "fieldCluster": "Arts & Humanities",
        "field": "humanities",
        "uni": "Jagannath University",
        "session": "2016",
        "role": "Medical information officer · Popular pharmaceutical",
        "good": "Inspiring Professor",
        "bad": "All",
        "whoShould": "All",
        "whoShouldnt": "All",
        "opportunities": "Teacher",
        "again": "no",
        "alternative": "i have no interest"
    },
    {
        "verified": true,
        "id": "resp_029",
        "age": "27",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "development-studies",
        "subjectName": "Development Studies",
        "fieldCluster": "Social Sciences",
        "field": "social-science",
        "uni": "University of Dhaka",
        "session": "2016",
        "role": "Co-ordinator",
        "good": "Field visits, experienced Professors",
        "bad": "Mathematical courses",
        "whoShould": "Those who are interested in working in an NGO for their professional career",
        "whoShouldnt": "Those who want to focus on a particular aspect because it is a multidimensional subject.",
        "opportunities": "NGO, Bank",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_030",
        "age": "29",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "statistics",
        "subjectName": "Statistics",
        "fieldCluster": "Natural Sciences",
        "field": "science",
        "uni": "Jahangirnagar University",
        "session": "2014",
        "role": "Teacher",
        "good": "I was not quite happy with this course since it was a hard subject. But teacher are there to make the topic easier.",
        "bad": "It was hard for me to understand",
        "whoShould": "Whoever takes this subject, they have to sincerely study this particular subject otherwise no one can understands the topics.",
        "whoShouldnt": "Its a math related subjects so if you are weak in mathematics, you should avoid it",
        "opportunities": "There are many possiblities of this subject.",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_031",
        "age": "33",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "mathematics",
        "subjectName": "Mathematics",
        "fieldCluster": "Natural Sciences",
        "field": "science",
        "uni": "University of Dhaka",
        "session": "2008",
        "role": "CEO · Hit the trail",
        "good": "Calculus is good topics for a student.",
        "bad": "Topology, fuzzy mathematics are hard topics.. And teachers are not fully efficient to teach",
        "whoShould": "Whose basic knowledge about math is very good.",
        "whoShouldnt": "Those are not good in math.",
        "opportunities": "Banker, data analyst etc",
        "again": "no",
        "alternative": "I would choose Computer science subject... Because of demand in higher studies."
    },
    {
        "verified": true,
        "id": "resp_032",
        "age": "29",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "cse",
        "subjectName": "Computer Science & Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "American International University-Bangladesh (AIUB)",
        "session": "15-1",
        "role": "Senior Video Editor · BongoBd",
        "good": "Making the App for Aiub Canteen Management",
        "bad": "Coding has no color in back end So, It's boring sometime",
        "whoShould": "Who likes mathematics a lot.",
        "whoShouldnt": "Who doesn’t like mathematics.",
        "opportunities": "Canbt explain in words coz the world is moving with Computer so that opportunities are it's limitless.",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_033",
        "age": "28",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "clothing-textile",
        "subjectName": "Clothing & Textile",
        "fieldCluster": "Arts & Humanities",
        "field": "humanities",
        "uni": "Government College of Applied Human Science",
        "session": "2013",
        "role": "*****",
        "good": "Getting scholarship from university",
        "bad": "Lackings of lab facilities",
        "whoShould": "Those really want to do hard work, passionate to their work and capable to handle a lot of work pressure and can sacrifice endless weekend",
        "whoShouldnt": "Those aren’t willing to work without time limitations and can't cope up with work load",
        "opportunities": "Can make a great career if anyone can sacrifice their first few years without expectations and learn everything with sincerity",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_034",
        "age": "30",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "physics",
        "subjectName": "Physics",
        "fieldCluster": "Natural Sciences",
        "field": "science",
        "uni": "University of Dhaka",
        "session": "2012",
        "role": "Housewife",
        "good": "I don’t have any good experiences",
        "bad": "Challenging topics",
        "whoShould": "Who is interested in physics in their school or college days and also good in mathematics",
        "whoShouldnt": "Who isn’t good in mathematics",
        "opportunities": "Research opportunities, foreign job opportunities",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_035",
        "age": "33",
        "city": "Chattogram",
        "country": "BD",
        "subjectSlug": "linguistics",
        "subjectName": "Linguistics",
        "fieldCluster": "Arts & Humanities",
        "field": "humanities",
        "uni": "University of Dhaka",
        "session": "2010",
        "role": "Officer",
        "good": "Got to know versatility about language.",
        "bad": "Not so much job opportunity in BD.",
        "whoShould": "Who is enthusiastic to teaching.",
        "whoShouldnt": "Who is not interested in language and grammar.",
        "opportunities": "Teaching, translator, interpreter.",
        "again": "no",
        "alternative": "Anthropology or Development Studies. Because I have found them more interesting and those subjects have more job facilities I guess."
    },
    {
        "verified": true,
        "id": "resp_036",
        "age": null,
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "accounting",
        "subjectName": "Accounting",
        "fieldCluster": "Business & Commerce",
        "field": "business",
        "uni": "Stamford University Bangladesh",
        "session": "2015",
        "role": "Full-Stack Developer {Laravel (PHP), ReactJS (JavaScript), WordPress (PHP)} · I prefer not to disclose",
        "good": "I was very interested in CA (Chartered Accountant); therefore, I picked accounting as a major subject, and I had some external/internal desire related to accounting. Well, I was good in math at an early age, and it was easy to solve issues and manipulate leading places. I want to say a good, honest, and hard-working person can change a company's financial status, except if he/she is not.",
        "bad": "Sorry to say: 1. We do not have much good teachers to teach accounting 2. Education institutions still follow the theoretical case study 3. Teachers and authorities are arrogant 4. Teachers and people think accounting is an easy subject but accounting is one of the world's hardest subject 5. Education institutions and organizations are not well concerned about accounts, and that's one of the reasons we are falling Some points: Resources come from experience and willingness; if you don't have them, then a \"lack of resources\" will arise. \"Challenging topics\" are most welcome, but who will bring them to students? While some of us (we know who they are) have destroyed our system. No doubt, our country is just focusing on marks like 4/4, 3.8/4, and so on. So what do we expect except for the \"poor course structure\"?",
        "whoShould": "If you have your own and your parents' business, go for it without hesitation. If you are a good, honest, hard-working person and good at math, then go for it.",
        "whoShouldnt": "1. The liar must not take on this subject. 2. Those who are not good, honest, hard-working, and proficient at math. 3. Those who have no patience. 4. Greedy people must stay away from accounting (please).",
        "opportunities": "Very good, but you must be capable of building your base.",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_037",
        "age": "27",
        "city": "Atlanta",
        "country": "US",
        "subjectSlug": "cse",
        "subjectName": "Computer Science & Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "BRAC University",
        "session": "2017",
        "role": "Graduate Research Assistant · Kennesaw state university",
        "good": "it has been highly rewarding, with highlights including becoming a semi-finalist in Esho Robot Banai, Bangladesh's first robotics reality show, and competing against top universities. I earned a merit-based scholarship and High Distinction at BRAC University, secured top positions in programming contests, and published a paper, all of which enriched my knowledge and skills.",
        "bad": "should increase involvement with industry",
        "whoShould": "Anyone with the interest",
        "whoShouldnt": "thinking it will make you successful",
        "opportunities": "Software Development Artificial Intelligence & Machine Learning Data Science & Analytics Cybersecurity Robotics Cloud Computing Game Development Internet of Things (IoT) Research & Academia Entrepreneurship etc",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_038",
        "age": "29",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "physics",
        "subjectName": "Physics",
        "fieldCluster": "Natural Sciences",
        "field": "science",
        "uni": "University of Dhaka",
        "session": "2013",
        "role": "Student",
        "good": "Teacher used to discourage",
        "bad": "Bad behaviour of teachers",
        "whoShould": "He /her will take this subject if passion in this subject subject.",
        "whoShouldnt": "Depend on he/her passion",
        "opportunities": "There is many opportunity if cgpa will good.",
        "again": "no",
        "alternative": "Computer Science"
    },
    {
        "verified": true,
        "id": "resp_039",
        "age": "27",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "social-work",
        "subjectName": "Social Work",
        "fieldCluster": "Social Sciences",
        "field": "social-science",
        "uni": "Lalmatia Mahila College",
        "session": "2016",
        "role": "Brand and groth manager · Inception group",
        "good": "One of the best experiences while studying this subject was working on collaborative projects that highlighted the differences between centralized and decentralized education systems. These projects encouraged teamwork and critical thinking, making the learning process enjoyable. Additionally, discussions led by inspiring professors who shared real-life examples of policy impacts made the subject more relatable and engaging. The coursework often included case studies and creative assignments, which made it both fun and intellectually rewarding…",
        "bad": "A challenging aspect was the lack of practical application in some coursework, which made it feel disconnected from real-world scenarios. Additionally, the heavy focus on memorization over critical thinking sometimes reduced engagement and understanding.",
        "whoShould": "This subject is ideal for students passionate about education reform, policy-making, or understanding the broader impact of centralized systems on society. It’s especially suited for those aspiring to work in education administration, public policy, or social development sectors.",
        "whoShouldnt": "Students who prefer hands-on, technical fields or are not interested in theoretical discussions about education systems might find this subject less engaging. It’s not ideal for those looking for immediate practical applications or careers unrelated to education or policy-making.",
        "opportunities": "Studying this subject can open doors to careers in education policy-making, school administration, curriculum development, and academic research. Graduates can also work with NGOs, government organizations, or international bodies focused on educational reform and development. Additionally, it provides a strong foundation for further studies in education, sociology, or public policy.",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_040",
        "age": "29",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "cse",
        "subjectName": "Computer Science & Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "Southeast University",
        "session": "2016",
        "role": "MBA · European Business Management Academy",
        "good": "- Solving engineering problems - Reading books - Doing maths",
        "bad": "- Poor course structure - No professional courses that will be helpful for further career - No inspiring professors, all seems to choose teaching profession so that they can show off or get advantage when going for foreign degrees - No investment lessons or guideline - Lack of interest in solving real problems, just some knowledge from books published before world war 2",
        "whoShould": "- Those who is up to gain some technical knowledge - Who is up for getting an engineering degree - Who wants to get into a university and pass time - Who wants to make sure s/he wants to fullfil the basic criteria of Bangladesh job marketplace that you need to be graduated to get this job",
        "whoShouldnt": "- Those who are very much optimistic and tech enthusiast and hoping he will get expected outcome - Those who want to get market standard salary job - Those who are business minded",
        "opportunities": "Can become CTO or Tech business entrepreneure at most",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_041",
        "age": "23",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "bba",
        "subjectName": "Business Administration (BBA)",
        "fieldCluster": "Business & Commerce",
        "field": "business",
        "uni": "Bangladesh University of Professionals (BUP)",
        "session": "2021",
        "role": "Content Marketing Intern · Sheba.Xyz",
        "good": "Inspiring Professors",
        "bad": "Poor Course Structure",
        "whoShould": "Creative Person",
        "whoShouldnt": "Procrastinator",
        "opportunities": "Sales, Branding",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_042",
        "age": "21",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "bba",
        "subjectName": "Business Administration (BBA)",
        "fieldCluster": "Business & Commerce",
        "field": "business",
        "uni": "Bangladesh Maritime University",
        "session": "2022",
        "role": "Project Manager · Genius Prep Academy",
        "good": "Specialized field gives you an advantage along with the general ones.",
        "bad": "Many unexplored factors & lack of resources to dig into them.",
        "whoShould": "Specialized BBA, Specified job fields along with the general ones, Interesting studies, Scopes for research, these are one the reasons for choosing this subject.",
        "whoShouldnt": "Less availability of resources in BD, Less expert people to teach, Not many people you relate with your studies.",
        "opportunities": "High paying jobs, easy to get scholarships, being a faculty for this discipline as it's still expanding & growing & etc",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_043",
        "age": "28",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "cse",
        "subjectName": "Computer Science & Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "University of Asia Pacific",
        "session": "2015",
        "role": "Designer · PDS International",
        "good": "Learning about new technologies with potential applications, learning and improvement in problem-solving skills.",
        "bad": "Too much thinking for Coding.",
        "whoShould": "Critical thinker and problem solver.",
        "whoShouldnt": "Who's not potential in his career!",
        "opportunities": "Yes, More.",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_044",
        "age": "28",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "mathematics",
        "subjectName": "Applied Mathematics",
        "fieldCluster": "Natural Sciences",
        "field": "science",
        "uni": "University of Dhaka",
        "session": "2013",
        "role": "Frontend Developer (ReactJS) · Wellmax IT Ltd.",
        "good": "Got relieved from DU Physics Department",
        "bad": "Unfortunately read Physics throughout 4 years of Bachelor Degree",
        "whoShould": "Any student who are enthusiastic in both Mathematics and Physics",
        "whoShouldnt": "Who doesn't love any of Physics or Mathematics",
        "opportunities": "The world is yours to conquer. Mathematician has no obligation to achieve any career goal.",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_045",
        "age": "22",
        "city": "Chittagong",
        "country": "BD",
        "subjectSlug": "botany",
        "subjectName": "Botany",
        "fieldCluster": "Life & Earth Sciences",
        "field": "environmental",
        "uni": "University of Chittagong",
        "session": "2022",
        "role": "Student",
        "good": "Always teachers motivate to explore and invent new methods to make lives easy for humans and not to increase pollution, diseases that now become harmful for earth and humans. Also they inspire to become a best botanist to know each and every details about trees and their effects, benefits in earth and humans lives.",
        "bad": "I am not good at memorized knowledge so have to face difficulties to memorize scientific names in some topics.",
        "whoShould": "Those have interest in research about trees and their effects,benefits in nature and humans lives.",
        "whoShouldnt": "Those don't have interest in researching related this subject.",
        "opportunities": "Researching institutions, medicine companies,BCS,non government job sectors.",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_046",
        "age": "21",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "bba",
        "subjectName": "Business Administration (BBA)",
        "fieldCluster": "Business & Commerce",
        "field": "business",
        "uni": "East West University",
        "session": "2016",
        "role": "Managing director · Koli Agro Farm Includes Limited",
        "good": "Inspiring proffer was Zohur sir he motivate us every single time",
        "bad": "My most challenging topic was economics",
        "whoShould": "Who has the passion to do business",
        "whoShouldnt": "Who did not want study maths",
        "opportunities": "Doing business, banks jobs , multinational companies accountants or manager jobs",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_047",
        "age": "26",
        "city": "Comilla",
        "country": "BD",
        "subjectSlug": "civil-engineering",
        "subjectName": "Civil Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "Bangabandhu Sheikh Mujibur Rahman Aviation & Aerospace University",
        "session": "2022",
        "role": "Student",
        "good": "Durning Laboratory classes",
        "bad": "Lack of practical classes",
        "whoShould": "Who loves math",
        "whoShouldnt": "Who hates geometry",
        "opportunities": "Structural or environment or transport Sector",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_048",
        "age": "26",
        "city": "Sydney",
        "country": "AU",
        "subjectSlug": "cse",
        "subjectName": "Computer Science & Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "Daffodil International University",
        "session": "2018",
        "role": "Master's in Information Technology · Central Queensland University",
        "good": "Research papers articles, advance computing projects and so on",
        "bad": "Lack of international resources and weak curse structure",
        "whoShould": "A person who is enthusiastic about computer science and algorithms",
        "whoShouldnt": "Who doesn't want to learn regularly",
        "opportunities": "IT industry job facilities and new startup companies",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_049",
        "age": "27",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "bangla",
        "subjectName": "Bangla",
        "fieldCluster": "Arts & Humanities",
        "field": "humanities",
        "uni": "Jagannath University",
        "session": "2016",
        "role": "Lecturer · Milestone college",
        "good": "This subject gives me the motivation to live",
        "bad": "I am in financial trouble to teach in Bengali",
        "whoShould": "Who are Rich",
        "whoShouldnt": "N/a",
        "opportunities": "Good",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_050",
        "age": "30",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "mathematics",
        "subjectName": "Mathematics",
        "fieldCluster": "Natural Sciences",
        "field": "science",
        "uni": "Jagannath University",
        "session": "2011",
        "role": "SENIOR OFFICER · SONALI BANK PLC",
        "good": "Inspiring Professors",
        "bad": "Lack of resources",
        "whoShould": "Because Mathematics is the mother of Science",
        "whoShouldnt": "It is quite hard",
        "opportunities": "PhD, if possible",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_051",
        "age": "31",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "cse",
        "subjectName": "Computer Science & Engineering",
        "fieldCluster": "Engineering & Technology",
        "field": "technology",
        "uni": "Stamford University Bangladesh",
        "session": "2013",
        "role": "SOFTWARE ENGINEER · AQUALINK BANGLADESH",
        "good": "fun coursework",
        "bad": "poor course structure",
        "whoShould": "tech-savvy people",
        "whoShouldnt": "those who does not like to learning new things frequently",
        "opportunities": "the best opportunities are AI related topics",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_052",
        "age": "27",
        "city": "Dhaka",
        "country": "BD",
        "subjectSlug": "bba",
        "subjectName": "Business Administration (BBA)",
        "fieldCluster": "Business & Commerce",
        "field": "business",
        "uni": "Bangladesh University of Business & Technology (BUBT)",
        "session": "2021",
        "role": "Visa processing officer · PDS International",
        "good": "Making advertisement based on assigned product while in a group project and getting highly praised for it by my favourite teacher",
        "bad": "As marketing requires interaction with people, it was quite challenging do survey for class assignments.",
        "whoShould": "People who are confident and can communicate well. A strong convincing mindset will help you a lot",
        "whoShouldnt": "Quite, introvert individuals should avoid this subject.",
        "opportunities": "A lot actually! Marketing is needed in almost every field",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_053",
        "age": "30",
        "city": "Norfolk",
        "country": "US",
        "subjectSlug": "physics",
        "subjectName": "Physics",
        "fieldCluster": "Natural Sciences",
        "field": "science",
        "uni": "University of Dhaka",
        "session": "2013",
        "role": "Graduate Student · Old Dominion University",
        "good": "Some of our professors were very helpful, inspiring and down to earth. Doing the experiments in lab courses were very exciting to me as we could gather practical experience of what we were learning in theoretical courses.",
        "bad": "It’s undoubtedly a very hard subject. And most of the lectures were not at all organized. A large number of Professors used to demotivate students and scare the shit out them.",
        "whoShould": "If you are very passionate about knowing the cause of how everything works and love mathematics as well, this is the subject for you. You need to hard working and have very good analytical skills.",
        "whoShouldnt": "Don’t take it if you are not a fan of Physics and Math",
        "opportunities": "Plenty. You can go anywhere in academia or industry. You can switch to any other related subjects.",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_054",
        "age": "29",
        "city": "Reno",
        "country": "US",
        "subjectSlug": "physics",
        "subjectName": "Physics",
        "fieldCluster": "Natural Sciences",
        "field": "science",
        "uni": "University of Dhaka",
        "session": "2013",
        "role": "Teaching Assistant · University of Nevada Reno",
        "good": "Interesting topics and fun coursework",
        "bad": "Poor course structure",
        "whoShould": "Anyone interested in Physics",
        "whoShouldnt": "Anyone looking for only money",
        "opportunities": "Laboratory works and research",
        "again": "yes",
        "alternative": null
    },
    {
        "verified": true,
        "id": "resp_055",
        "age": "29",
        "city": "Syracuse",
        "country": "US",
        "subjectSlug": "physics",
        "subjectName": "Physics",
        "fieldCluster": "Natural Sciences",
        "field": "science",
        "uni": "University of Dhaka",
        "session": "2013",
        "role": "Graduate Research Assistant · Syracuse University",
        "good": "Had some really good professors",
        "bad": "Course structure was a bit off, e.g., we never received proper training in programming which is a prerequisite for solving Physics problems while we had to study random subjects which we never required in the end.",
        "whoShould": "Someone who has a proper understanding of what draws them towards this subject and are truly passionate about it.",
        "whoShouldnt": "Just because they want to get through undergraduate and are ready to take up any challenge that life might throw at them.",
        "opportunities": "Higher study abroad and possible chances of switching to any subject of their liking.",
        "again": "no",
        "alternative": "Chemistry. This subject was something I was always passionate about and could perform well naturally."
    },
    {
        "verified": true,
        "id": "resp_056",
        "age": "27",
        "city": "Suwon",
        "country": "KR",
        "subjectSlug": "journalism",
        "subjectName": "Journalism & Media Studies",
        "fieldCluster": "Social Sciences",
        "field": "social-science",
        "uni": "Jahangirnagar University",
        "session": "45",
        "role": "Student · Ajou university",
        "good": "Fun to work with camera, scope of being creative with content creation",
        "bad": "Lack of professional recognition and opportunity with a bare minimum salary",
        "whoShould": "Nobody should take it in Bangladesh so that tv channel authorities prioritize giving a better wage to journalists, also the life security of journalists is also a concern.",
        "whoShouldnt": "Everyone.",
        "opportunities": "Journalist, Anchor, content creator, advertiser, teacher, this subject opens door for many possible professions in future",
        "again": "no",
        "alternative": "Culinary Art or A subject focused on content creation rather than journalism."
    }
];

  // Helper — compute confidence tier from current testimonial count.
  // Use the static `confidence` field on each subject for SSR/initial render;
  // re-derive at runtime if data grows.
  function computeConfidence(slug, hasProfile) {
    const count = testimonials.filter(t => t.subjectSlug === slug).length;
    if (hasProfile && count >= 8) return "verified";
    if (hasProfile || count >= 3)  return "emerging";
    return "listed";
  }

  return { subjects, testimonials, FIELDS, computeConfidence };
})();
