// EduPath BD — Official university registry
// Source: University Grants Commission of Bangladesh (ugc-universities.gov.bd)
// Last verified: 2025–2026 academic year
// Only active institutions included (defunct/suspended removed)

(function () {
  window.UGCData = {

    // ─── Country / city lookup ─────────────────────────────────────────────
    cities: {
      dhaka:       "Dhaka",
      chittagong:  "Chittagong",
      rajshahi:    "Rajshahi",
      khulna:      "Khulna",
      sylhet:      "Sylhet",
      mymensingh:  "Mymensingh",
      gazipur:     "Gazipur",
      dinajpur:    "Dinajpur",
      tangail:     "Tangail",
      patuakhali:  "Patuakhali",
      comilla:     "Comilla",
      noakhali:    "Noakhali",
      jessore:     "Jessore (Jashore)",
      pabna:       "Pabna",
      rangpur:     "Rangpur",
      gopalganj:   "Gopalganj",
      barishal:    "Barishal",
      kushtia:     "Kushtia",
      natore:      "Natore",
      savar:       "Savar (near Dhaka)",
      narayanganj: "Narayanganj",
    },

    // ─── Public universities ───────────────────────────────────────────────
    public: [
      { id:"du",    name:"University of Dhaka",                                    short:"DU",    city:"dhaka",      website:"www.du.ac.bd",    focus:"general",     tier:"top" },
      { id:"ru",    name:"University of Rajshahi",                                 short:"RU",    city:"rajshahi",   website:"www.ru.ac.bd",    focus:"general",     tier:"top" },
      { id:"bau",   name:"Bangladesh Agricultural University",                     short:"BAU",   city:"mymensingh", website:"www.bau.edu.bd",  focus:"agriculture", tier:"top" },
      { id:"buet",  name:"Bangladesh University of Engineering & Technology",      short:"BUET",  city:"dhaka",      website:"www.buet.ac.bd",  focus:"engineering", tier:"top" },
      { id:"cu",    name:"University of Chittagong",                               short:"CU",    city:"chittagong", website:"www.cu.ac.bd",    focus:"general",     tier:"top" },
      { id:"ju",    name:"Jahangirnagar University",                               short:"JU",    city:"savar",      website:"www.juniv.edu",   focus:"general",     tier:"top" },
      { id:"iu",    name:"Islamic University, Bangladesh",                         short:"IU",    city:"kushtia",    website:"www.iu.ac.bd",    focus:"general",     tier:"strong" },
      { id:"sust",  name:"Shahjalal University of Science & Technology",           short:"SUST",  city:"sylhet",     website:"www.sust.edu",    focus:"science",     tier:"top" },
      { id:"ku",    name:"Khulna University",                                      short:"KU",    city:"khulna",     website:"www.ku.ac.bd",    focus:"general",     tier:"strong" },
      { id:"nu",    name:"National University",                                    short:"NU",    city:"gazipur",    website:"www.nu.edu.bd",   focus:"general",     tier:"accessible", note:"Affiliates hundreds of colleges nationwide" },
      { id:"bou",   name:"Bangladesh Open University",                             short:"BOU",   city:"gazipur",    website:"www.bou.ac.bd",   focus:"general",     tier:"accessible", note:"Distance education" },
      { id:"hstu",  name:"Hajee Mohammad Danesh Science & Technology University",  short:"HSTU",  city:"dinajpur",   website:"www.hstu.ac.bd",  focus:"science",     tier:"strong" },
      { id:"mbstu", name:"Mawlana Bhashani Science & Technology University",       short:"MBSTU", city:"tangail",    website:"www.mbstu.ac.bd", focus:"science",     tier:"strong" },
      { id:"pstu",  name:"Patuakhali Science And Technology University",           short:"PSTU",  city:"patuakhali", website:"www.pstu.ac.bd",  focus:"agriculture", tier:"strong" },
      { id:"sau",   name:"Sher-e-Bangla Agricultural University",                  short:"SAU",   city:"dhaka",      website:"www.sau.edu.bd",  focus:"agriculture", tier:"strong" },
      { id:"cuet",  name:"Chittagong University of Engineering & Technology",      short:"CUET",  city:"chittagong", website:"www.cuet.ac.bd",  focus:"engineering", tier:"top" },
      { id:"ruet",  name:"Rajshahi University of Engineering & Technology",        short:"RUET",  city:"rajshahi",   website:"www.ruet.ac.bd",  focus:"engineering", tier:"top" },
      { id:"kuet",  name:"Khulna University of Engineering & Technology",          short:"KUET",  city:"khulna",     website:"www.kuet.ac.bd",  focus:"engineering", tier:"top" },
      { id:"duet",  name:"Dhaka University of Engineering & Technology",           short:"DUET",  city:"gazipur",    website:"www.duet.ac.bd",  focus:"engineering", tier:"strong", note:"Accepts diploma holders" },
      { id:"nstu",  name:"Noakhali Science & Technology University",               short:"NSTU",  city:"noakhali",   website:"www.nstu.edu.bd", focus:"science",     tier:"strong" },
      { id:"jnu",   name:"Jagannath University",                                   short:"JnU",   city:"dhaka",      website:"www.jnu.ac.bd",   focus:"general",     tier:"strong" },
      { id:"cou",   name:"Comilla University",                                     short:"CoU",   city:"comilla",    website:"www.cou.ac.bd",   focus:"general",     tier:"strong" },
      { id:"jkkniu",name:"Jatiya Kabi Kazi Nazrul Islam University",              short:"JKKNIU",city:"mymensingh",  website:"www.jkkniu.edu.bd",focus:"arts",       tier:"strong" },
      { id:"cvasu", name:"Chittagong Veterinary and Animal Sciences University",   short:"CVASU", city:"chittagong", website:"www.cvasu.ac.bd", focus:"veterinary",  tier:"strong" },
      { id:"just",  name:"Jessore University of Science & Technology",             short:"JUST",  city:"jessore",    website:"www.just.edu.bd", focus:"science",     tier:"strong" },
      { id:"pust",  name:"Pabna University of Science and Technology",             short:"PUST",  city:"pabna",      website:"www.pust.ac.bd",  focus:"science",     tier:"strong" },
      { id:"brur",  name:"Begum Rokeya University, Rangpur",                       short:"BRUR",  city:"rangpur",    website:"www.brur.ac.bd",  focus:"general",     tier:"strong" },
      { id:"bup",   name:"Bangladesh University of Professionals",                 short:"BUP",   city:"dhaka",      website:"www.bup.edu.bd",  focus:"general",     tier:"strong", note:"Military-affiliated; civilians admitted" },
      { id:"bsmrstu",name:"Gopalganj Science & Technology University",             short:"BSMRSTU",city:"gopalganj", website:"www.bsmrstu.edu.bd",focus:"science",   tier:"strong" },
      { id:"butex", name:"Bangladesh University of Textiles",                      short:"BUTEX", city:"dhaka",      website:"www.butex.edu.bd", focus:"textile",    tier:"strong" },
      { id:"ubar",  name:"University of Barishal",                                 short:"UBar",  city:"barishal",   website:"www.bu.ac.bd",    focus:"general",     tier:"strong" },
      { id:"iut",   name:"Islamic University of Technology",                       short:"IUT",   city:"gazipur",    website:"www.iutoic-dhaka.edu", focus:"engineering", tier:"top", note:"OIC-member country students; tuition-free" },
      { id:"sau_sylhet", name:"Sylhet Agricultural University",                    short:"SAU-Syl",city:"sylhet",    website:"www.sau.ac.bd",   focus:"agriculture", tier:"strong" },
    ],

    // ─── Private universities (active, established programmes) ────────────
    private: [
      { id:"nsu",    name:"North South University",                          short:"NSU",   city:"dhaka",      website:"www.northsouth.edu",         tier:"top",    annualCostBDT:"160,000–200,000" },
      { id:"iub",    name:"Independent University, Bangladesh",              short:"IUB",   city:"dhaka",      website:"www.iub.edu.bd",             tier:"top",    annualCostBDT:"150,000–190,000" },
      { id:"iiuc",   name:"International Islamic University Chittagong",     short:"IIUC",  city:"chittagong", website:"www.iiuc.ac.bd",             tier:"strong", annualCostBDT:"80,000–130,000" },
      { id:"aust",   name:"Ahsanullah University of Science and Technology", short:"AUST",  city:"dhaka",      website:"www.aust.edu",               tier:"strong", annualCostBDT:"120,000–160,000" },
      { id:"aiub",   name:"American International University-Bangladesh",    short:"AIUB",  city:"dhaka",      website:"www.aiub.ac.bd",             tier:"top",    annualCostBDT:"140,000–180,000" },
      { id:"ewu",    name:"East West University",                            short:"EWU",   city:"dhaka",      website:"www.ewubd.edu",              tier:"strong", annualCostBDT:"110,000–150,000" },
      { id:"uap",    name:"University of Asia Pacific",                      short:"UAP",   city:"dhaka",      website:"www.uap-bd.edu",             tier:"strong", annualCostBDT:"110,000–150,000" },
      { id:"bracu",  name:"BRAC University",                                 short:"BRAC",  city:"dhaka",      website:"www.bracu.ac.bd",            tier:"top",    annualCostBDT:"160,000–210,000" },
      { id:"lus",    name:"Leading University",                              short:"LUS",   city:"sylhet",     website:"www.lus.ac.bd",              tier:"strong", annualCostBDT:"80,000–120,000" },
      { id:"uoda",   name:"University of Development Alternative",           short:"UODA",  city:"dhaka",      website:"www.uoda.edu.bd",            tier:"good",   annualCostBDT:"70,000–100,000" },
      { id:"premier",name:"Premier University",                              short:"Premier",city:"chittagong",website:"www.puc.ac.bd",             tier:"good",   annualCostBDT:"70,000–110,000" },
      { id:"diu",    name:"Daffodil International University",               short:"DIU",   city:"dhaka",      website:"www.daffodilvarsity.edu.bd", tier:"strong", annualCostBDT:"100,000–140,000" },
      { id:"stamford",name:"Stamford University Bangladesh",                 short:"Stamford",city:"dhaka",    website:"www.stamforduniversity.edu.bd",tier:"good",  annualCostBDT:"80,000–110,000" },
      { id:"seu",    name:"Southeast University",                            short:"SEU",   city:"dhaka",      website:"www.seu.edu.bd",             tier:"good",   annualCostBDT:"80,000–110,000" },
      { id:"green",  name:"Green University of Bangladesh",                  short:"Green", city:"dhaka",      website:"www.green.edu.bd",           tier:"good",   annualCostBDT:"80,000–120,000" },
      { id:"eastern",name:"Eastern University",                              short:"EU",    city:"dhaka",      website:"www.easternuni.edu.bd",      tier:"good",   annualCostBDT:"75,000–110,000" },
      { id:"metro",  name:"Metropolitan University",                         short:"Metro", city:"sylhet",     website:"www.metrouni.edu.bd",        tier:"good",   annualCostBDT:"70,000–100,000" },
      { id:"uttara", name:"Uttara University",                               short:"UU",    city:"dhaka",      website:"www.uttarauniversity.edu.bd", tier:"good",  annualCostBDT:"70,000–100,000" },
      { id:"uiu",    name:"United International University",                 short:"UIU",   city:"dhaka",      website:"www.uiu.ac.bd",              tier:"strong", annualCostBDT:"120,000–160,000" },
      { id:"bubt",   name:"Bangladesh University of Business & Technology",  short:"BUBT",  city:"dhaka",      website:"www.bubt.edu.bd",            tier:"strong", annualCostBDT:"90,000–130,000" },
      { id:"uits",   name:"University of Information Technology & Sciences", short:"UITS",  city:"dhaka",      website:"www.uits.edu.bd",            tier:"good",   annualCostBDT:"80,000–110,000" },
      { id:"ulab",   name:"University of Liberal Arts Bangladesh",           short:"ULAB",  city:"dhaka",      website:"www.ulab.edu.bd",            tier:"strong", annualCostBDT:"110,000–150,000" },
      { id:"asa",    name:"ASA University Bangladesh",                       short:"ASAUB", city:"dhaka",      website:"www.asaub.edu.bd",           tier:"good",   annualCostBDT:"75,000–110,000" },
      { id:"edu",    name:"East Delta University",                           short:"EDU",   city:"chittagong", website:"www.eastdelta.edu.bd",       tier:"strong", annualCostBDT:"90,000–130,000" },
      { id:"varendra",name:"Varendra University",                            short:"VU",    city:"rajshahi",   website:"www.vu.edu.bd",              tier:"good",   annualCostBDT:"70,000–100,000" },
      { id:"hamdard",name:"Hamdard University Bangladesh",                   short:"HUB",   city:"dhaka",      website:"www.hamdarduniversity.edu.bd",tier:"good",  annualCostBDT:"80,000–120,000", note:"Strong in pharmacy/health" },
      { id:"buft",   name:"BGMEA University of Fashion & Technology",        short:"BUFT",  city:"dhaka",      website:"www.buft.edu.bd",            tier:"strong", annualCostBDT:"90,000–130,000", note:"Specialist in textile/fashion" },
      { id:"neub",   name:"North East University Bangladesh",                short:"NEUB",  city:"sylhet",     website:"www.neub.edu.bd",            tier:"good",   annualCostBDT:"70,000–100,000" },
      { id:"kyau",   name:"Khwaja Yunus Ali University",                     short:"KYAU",  city:"natore",     website:"www.kyau.edu.bd",            tier:"good",   annualCostBDT:"70,000–110,000", note:"Strong in medical/health" },
      { id:"portcity",name:"Port City International University",             short:"PCIU",  city:"chittagong", website:"www.portcity.edu.bd",        tier:"good",   annualCostBDT:"70,000–100,000" },
      { id:"ciu",    name:"Chittagong Independent University",               short:"CIU",   city:"chittagong", website:"www.ciu.edu.bd",             tier:"good",   annualCostBDT:"70,000–100,000" },
      { id:"ndub",   name:"Notre Dame University Bangladesh",                short:"NDUB",  city:"dhaka",      website:"www.ndub.edu.bd",            tier:"good",   annualCostBDT:"80,000–110,000" },
      { id:"gub",    name:"German University Bangladesh",                    short:"GUB",   city:"dhaka",      website:"www.gub.edu.bd",             tier:"good",   annualCostBDT:"90,000–130,000" },
      { id:"baust",  name:"Bangladesh Army University of Science and Technology (Saidpur)", short:"BAUST", city:"dinajpur", website:"www.baust.edu.bd", tier:"strong", annualCostBDT:"100,000–140,000" },
      { id:"bauet",  name:"Bangladesh Army University of Engineering and Technology", short:"BAUET", city:"rajshahi", website:"www.bauet.ac.bd", tier:"strong", annualCostBDT:"100,000–140,000" },
      { id:"baiust", name:"Bangladesh Army International University of Science & Technology", short:"BAIUST", city:"comilla", website:"www.baiust.ac.bd", tier:"strong", annualCostBDT:"100,000–140,000" },
      { id:"cub",    name:"Canadian University of Bangladesh",               short:"CUB",   city:"dhaka",      website:"www.cub.edu.bd",             tier:"good",   annualCostBDT:"80,000–110,000" },
      { id:"ebaub",  name:"Exim Bank Agricultural University, Bangladesh",   short:"EBAUB", city:"chapai",     website:"www.ebaub.edu.bd",           tier:"good",   annualCostBDT:"70,000–100,000", note:"Agriculture focus" },
      { id:"smuct",  name:"Shanto-Mariam University of Creative Technology", short:"SMUCT", city:"dhaka",      website:"www.smuct.ac.bd",            tier:"good",   annualCostBDT:"80,000–110,000", note:"Design/architecture focus" },
      { id:"tuca",   name:"Tagore University of Creative Arts",              short:"TUCA",  city:"dhaka",      website:"www.tuca.edu.bd",            tier:"good",   annualCostBDT:"70,000–100,000" },
      { id:"iubat",  name:"International University of Business Agriculture & Technology", short:"IUBAT", city:"dhaka", website:"www.iubat.edu", tier:"good", annualCostBDT:"80,000–120,000" },
    ],

    // ─── International & CBHE ─────────────────────────────────────────────
    international: [
      { id:"iut",   name:"Islamic University of Technology",    short:"IUT",   city:"gazipur",  website:"www.iutoic-dhaka.edu",        note:"OIC institution; full scholarship for OIC-member students" },
      { id:"auw",   name:"Asian University for Women",          short:"AUW",   city:"chittagong",website:"www.auw.edu.bd",             note:"Women only; needs-blind scholarships available" },
    ],
    cbhe: [
      { id:"ucsi",  name:"UCSI University Malaysia (BD Campus)", short:"UCSI", city:"dhaka",    website:"www.bangladesh.ucsiuniversity.edu.my", note:"Malaysian university campus; dual-degree option" },
    ],

  }; // end UGCData
})();
