// EduPath BD — HSC/SSC → Undergraduate Subject Mapping
// Auto-generated by build_db.js — DO NOT EDIT MANUALLY

window.DB_HSCMapping = {
  "science": {
    "label": "Science",
    "hsc_subjects": [
      "Physics",
      "Chemistry",
      "Biology",
      "Higher Mathematics",
      "Mathematics",
      "ICT",
      "Agriculture"
    ],
    "maps_to": {
      "Physics": {
        "subjects": [
          "cse",
          "eee",
          "civil-engineering",
          "mechanical-engineering",
          "physics",
          "architecture",
          "kuet-others"
        ],
        "weight": 0.9
      },
      "Chemistry": {
        "subjects": [
          "chemistry",
          "pharmacy",
          "agriculture",
          "food-technology",
          "chemical-engineering"
        ],
        "weight": 0.9
      },
      "Biology": {
        "subjects": [
          "pharmacy",
          "botany",
          "zoology",
          "agriculture",
          "fisheries",
          "microbiology",
          "genetic-engineering"
        ],
        "weight": 0.9
      },
      "Higher Mathematics": {
        "subjects": [
          "cse",
          "eee",
          "civil-engineering",
          "mechanical-engineering",
          "mathematics",
          "statistics",
          "physics",
          "architecture"
        ],
        "weight": 0.95
      },
      "Mathematics": {
        "subjects": [
          "cse",
          "eee",
          "mathematics",
          "statistics",
          "physics",
          "economics",
          "civil-engineering"
        ],
        "weight": 0.85
      },
      "ICT": {
        "subjects": [
          "cse",
          "eee",
          "information-technology"
        ],
        "weight": 0.8
      },
      "Agriculture": {
        "subjects": [
          "agriculture",
          "botany",
          "zoology",
          "food-technology",
          "fisheries"
        ],
        "weight": 0.85
      }
    }
  },
  "commerce": {
    "label": "Commerce",
    "hsc_subjects": [
      "Accounting",
      "Business Studies",
      "Finance & Banking",
      "Economics",
      "Statistics",
      "ICT"
    ],
    "maps_to": {
      "Accounting": {
        "subjects": [
          "accounting",
          "finance-banking",
          "bba",
          "management"
        ],
        "weight": 0.95
      },
      "Business Studies": {
        "subjects": [
          "bba",
          "management",
          "marketing",
          "hrm",
          "accounting"
        ],
        "weight": 0.9
      },
      "Finance & Banking": {
        "subjects": [
          "finance-banking",
          "economics",
          "bba",
          "accounting"
        ],
        "weight": 0.95
      },
      "Economics": {
        "subjects": [
          "economics",
          "development-studies",
          "public-administration",
          "statistics",
          "bba"
        ],
        "weight": 0.9
      },
      "Statistics": {
        "subjects": [
          "statistics",
          "economics",
          "mathematics",
          "cse"
        ],
        "weight": 0.85
      },
      "ICT": {
        "subjects": [
          "cse",
          "information-technology",
          "bba"
        ],
        "weight": 0.75
      }
    }
  },
  "arts": {
    "label": "Humanities (Arts)",
    "hsc_subjects": [
      "Bangla",
      "English",
      "History",
      "Civics",
      "Islamic Studies",
      "Geography",
      "Sociology",
      "Economics",
      "Logic",
      "Social Work"
    ],
    "maps_to": {
      "Bangla": {
        "subjects": [
          "bangla",
          "journalism",
          "history",
          "philosophy",
          "islamic-studies"
        ],
        "weight": 0.95
      },
      "English": {
        "subjects": [
          "english",
          "journalism",
          "law",
          "development-studies",
          "public-administration"
        ],
        "weight": 0.9
      },
      "History": {
        "subjects": [
          "history",
          "political-science",
          "islamic-studies",
          "philosophy",
          "sociology"
        ],
        "weight": 0.9
      },
      "Civics": {
        "subjects": [
          "political-science",
          "public-administration",
          "law",
          "sociology",
          "development-studies"
        ],
        "weight": 0.9
      },
      "Islamic Studies": {
        "subjects": [
          "islamic-studies",
          "arabic",
          "history",
          "philosophy",
          "bangla"
        ],
        "weight": 0.95
      },
      "Geography": {
        "subjects": [
          "geography",
          "environmental-science",
          "agriculture",
          "geology",
          "sociology"
        ],
        "weight": 0.85
      },
      "Sociology": {
        "subjects": [
          "sociology",
          "social-work",
          "anthropology",
          "development-studies",
          "political-science"
        ],
        "weight": 0.95
      },
      "Economics": {
        "subjects": [
          "economics",
          "development-studies",
          "bba",
          "statistics",
          "public-administration"
        ],
        "weight": 0.85
      },
      "Logic": {
        "subjects": [
          "philosophy",
          "law",
          "mathematics",
          "political-science"
        ],
        "weight": 0.8
      },
      "Social Work": {
        "subjects": [
          "social-work",
          "sociology",
          "development-studies",
          "public-administration"
        ],
        "weight": 0.95
      }
    }
  }
};

window.DB_InterestsMapping = {
  "coding": [
    "cse",
    "eee",
    "information-technology",
    "statistics"
  ],
  "mathematics": [
    "mathematics",
    "statistics",
    "cse",
    "eee",
    "physics",
    "economics"
  ],
  "building-things": [
    "civil-engineering",
    "mechanical-engineering",
    "architecture",
    "eee",
    "cse"
  ],
  "creative-design": [
    "architecture",
    "uiux",
    "journalism",
    "fine-arts",
    "bangla"
  ],
  "helping-people": [
    "social-work",
    "sociology",
    "development-studies",
    "public-administration",
    "law"
  ],
  "nature-environment": [
    "botany",
    "zoology",
    "agriculture",
    "geography",
    "fisheries",
    "environmental-science"
  ],
  "business-money": [
    "bba",
    "accounting",
    "finance-banking",
    "economics",
    "management",
    "marketing"
  ],
  "writing-language": [
    "bangla",
    "english",
    "journalism",
    "history",
    "philosophy"
  ],
  "law-governance": [
    "law",
    "political-science",
    "public-administration",
    "development-studies",
    "sociology"
  ],
  "lab-research": [
    "chemistry",
    "physics",
    "pharmacy",
    "botany",
    "zoology",
    "microbiology"
  ],
  "teaching": [
    "education",
    "bangla",
    "english",
    "mathematics",
    "history"
  ],
  "healthcare": [
    "pharmacy",
    "public-health",
    "botany",
    "zoology",
    "microbiology"
  ],
  "arts-culture": [
    "fine-arts",
    "bangla",
    "history",
    "islamic-studies",
    "philosophy",
    "journalism"
  ],
  "technology": [
    "cse",
    "eee",
    "information-technology",
    "mechanical-engineering",
    "architecture"
  ],
  "agriculture-food": [
    "agriculture",
    "food-technology",
    "botany",
    "zoology",
    "fisheries"
  ]
};
